// samples/EasyDataBasicDemo.React.Net10/ClientApp/src/components/EasyData.jsx
import { useEffect } from 'react';
import { EasyDataViewDispatcher } from '@easydata/crud';

export default function EasyData() {
    useEffect(() => {
        const viewDispatcher = new EasyDataViewDispatcher();
        viewDispatcher.run();

        return () => viewDispatcher.detach();
    }, []);

    return <div id="EasyDataContainer"></div>;
}

// samples/EasyDataBasicDemo.Angular.Net5/ClientApp/src/app/easydata/easydata.component.ts
import { AfterViewInit, Component, OnDestroy } from '@angular/core';
import { EasyDataViewDispatcher } from '@easydata/crud';

@Component({
  selector: 'app-easydata',
  template: '<div id="EasyDataContainer"></div>'
})
export class EasyDataComponent implements AfterViewInit, OnDestroy {

  private viewDispatcher: EasyDataViewDispatcher;

  constructor() {

  }

  ngAfterViewInit() {
    this.viewDispatcher = new EasyDataViewDispatcher();
    this.viewDispatcher.run();
  }

  ngOnDestroy() {
    this.viewDispatcher.detach();
  }
}
