// samples/EasyDataBasicDemo.Angular.Net5/ClientApp/src/app/easydata/easydata.component.ts
import { AfterViewInit, Component, OnDestroy } from '@angular/core';
import { EasyDataViewDispatcher } from '@easydata/crud';

@Component({
  selector: 'app-easydata',
  template: '<div id="EasyDataContainer"></div>'
})
export class EasyDataComponent implements AfterViewInit, OnDestroy {

  private viewDispatcher: EasyDataViewDispatcher;

  constructor() {

  }

  ngAfterViewInit() {
    this.viewDispatcher = new EasyDataViewDispatcher();
    this.viewDispatcher.run();
  }

  ngOnDestroy() {
    this.viewDispatcher.detach();
  }
}

// samples/EasyDataBasicDemo.React.Net6/ClientApp/src/components/EasyData.js
import React, { Component } from 'react';
import { EasyDataViewDispatcher } from '@easydata/crud';

export class EasyData extends Component {

  static displayName = EasyData.name;

  componentDidMount() {
    this.viewDispatcher = new EasyDataViewDispatcher();
    this.viewDispatcher.run();
  }

  render() {
    return (
      <div id="EasyDataContainer"></div>
    );
  }

  componentWillUnmount() {
    if (this.viewDispatcher)
        this.viewDispatcher.detach();
  }
}
